### ISSUE TITLE
Weird scrolling when modal popovers are activated

### ISSUE THREAD

**Issue by kassssc** [salonisaraf/CS506-bookstore-loyalty#10]
Summary: It is possible to scroll the base page when there is a popover modal over it

Description:
When an modal is open over the base page, when you use your fingers to scroll the page behind it (which is darkened) and it will be scrolled while the modal is still active.

Severity:
Minor, cosmetic UX stuff

Suggestions:
Disable the scroll on the base page.

**Comment by jschneid98** [comment]
All of the pages in the application are by default unscrollable, since the content is auto-formatted to fit the screen size.  The "scrolling" has to do with Chrome allowing you to scroll past the content of the application to white space, not with actually scrolling on the page, so we can't keep that from happening within the formatting of our app.  This issue could potentially be solved by hard-coding the formatting for every combination of browser and screen size, but this was beyond the scope of our prototype.
